apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  # project: {{ .Values.argoProject | default "default" }}
  # launchTemplate: 
  #   valueFrom:
  #   configMapKeyRef:
  #     name: config-map
  #     key: message
  subnetSelector:
    kubernetes.io/role/internal-elb: "1"
  securityGroupSelector: 
    "kubernetes.io/cluster/{{ .Values.karpenter.settings.aws.clusterName }}": "owned"
  instanceProfile: "{{ .Values.karpenter.settings.aws.clusterName }}-{{ .Values.karpenter.settings.aws.clusterName }}"
  tags:
    accountingEC2Tag: karpenter
    eks/nodegroup-name: {{ .Values.karpenter.settings.aws.clusterEndpoint }}
    eks/cluster-name: "{{ .Values.karpenter.settings.aws.clusterName }}"
  # amiFamily: "..."               # optional, resolves a default ami and userdata
  # amiSelector: { ... }           # optional, discovers tagged amis to override the amiFamily's default
  # userData: "..."                # optional, overrides autogenerated userdata with a merge semantic
  # tags: { ... }                  # optional, propagates tags to underlying EC2 resources
  # metadataOptions: { ... }       # optional, configures IMDS for the instance
  # blockDeviceMappings: [ ... ]   # optional, configures storage devices for the instance
  # detailedMonitoring: "..."      # optional, configures detailed monitoring for the instance
